apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686 # Jaeger Query UI
        - containerPort: 14268 # Jaeger Collector
        - containerPort: 16685
        - containerPort: 14250
        - containerPort: 4317
        - containerPort: 4318

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  type: NodePort
  ports:
  - name: http-query
    port: 16686
    targetPort: 16686
    nodePort: 30012
  - name: grpc-query
    port: 16685
    targetPort: 16685
  
---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
spec:
  selector:
    app: jaeger
  ports:
  - name: grpc-http
    port: 14250
    targetPort: 0
  - name: c-tchan-trft
    port: 14267
    targetPort: 0
  - name: http-c-binary-trft
    port: 14268
    targetPort: 0
  - name: otlp-grpc
    port: 4317
    targetPort: 0
  - name: otlp-http
    port: 4318
    targetPort: 0
  type: NodePort

