---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
      jaeger:
        protocols:
          grpc:
            endpoint: jaeger:14250
          thrift_compact:
            endpoint: jaeger:6831
          thrift_http:
            endpoint: jaeger:14268      
    processors:
    exporters:
      prometheus:
        endpoint: 'otel-prometheus-server:8889'
      logging:
        loglevel: debug
      otlp/jaeger:
        endpoint: 'jaeger-collector:4317'
        insecure: true
        insecure_skip_verify: true          
    service:
      pipelines:
        traces:
          receivers: [jaeger,otlp]
          processors: []
          exporters: [otlp/jaeger,logging]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [prometheus]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetrycollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetrycollector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetrycollector
    spec:
      containers:
      - name: otelcol
        ports:
          - containerPort: 8889 
          - containerPort: 14268
        args:
        - --config=/conf/collector.yaml
        image: otel/opentelemetry-collector:0.18.0
        volumeMounts:
        - mountPath: /conf
          name: collector-config
      volumes:
      - configMap:
          items:
          - key: collector.yaml
            path: collector.yaml
          name: collector-config
        name: collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector
spec:
  ports:
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: "8889"
    port: 8889
    targetPort: 8889
  - name: "14268"
    port: 14268
    targetPort: 14268
  selector:
    app.kubernetes.io/name: opentelemetrycollector
  type: ClusterIP
